import { Shield, AlertTriangle, CheckCircle, XCircle, Eye, Music, Type, Bot, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import RiskMeter from "./RiskMeter";

export interface AuditResult {
  videoTitle: string;
  channelName: string;
  overallRisk: number;
  checks: {
    id: string;
    label: string;
    status: "pass" | "fail" | "warning";
    score: number;
    detail: string;
  }[];
}

interface AuditDashboardProps {
  result: AuditResult;
}

const iconMap: Record<string, React.ElementType> = {
  reused: Eye,
  ai_content: Bot,
  metadata: Type,
  copyright: Music,
};

const statusConfig = {
  pass: { icon: CheckCircle, color: "text-accent", bg: "bg-accent/10 border-accent/20", label: "Pass" },
  fail: { icon: XCircle, color: "text-destructive", bg: "bg-destructive/10 border-destructive/20", label: "Fail" },
  warning: { icon: AlertTriangle, color: "text-yellow-400", bg: "bg-yellow-400/10 border-yellow-400/20", label: "Warning" },
};

const handleExportPDF = (result: AuditResult) => {
  const content = `
TUBECLEAR AI AUDIT REPORT
==========================
Generated: ${new Date().toLocaleString()}

Video/Channel: ${result.videoTitle}
Creator: ${result.channelName}
Overall Risk Score: ${result.overallRisk}/100

DETAILED CHECK RESULTS
-----------------------
${result.checks
  .map(
    (c) => `
${c.label}
  Status: ${c.status.toUpperCase()}
  Risk Score: ${c.score}/100
  Detail: ${c.detail}
`
  )
  .join("")}

---
Report generated by TubeClear AI • tubeclear.app
AI-Powered YouTube Monetization Shield
  `.trim();

  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `TubeClear-Report-${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
};

const AuditDashboard = ({ result }: AuditDashboardProps) => {
  return (
    <section className="container mx-auto px-6 py-12 space-y-8 animate-fade-in">
      {/* Header */}
      <div className="glass-card p-6 flex flex-col md:flex-row items-center gap-6">
        <RiskMeter score={result.overallRisk} label="Overall Risk" size="lg" />
        <div className="flex-1 text-center md:text-left">
          <h2 className="text-2xl font-bold">{result.videoTitle}</h2>
          <p className="text-muted-foreground">{result.channelName}</p>
          <div className="flex items-center gap-2 mt-3 justify-center md:justify-start">
            <Shield className="h-4 w-4 text-primary" />
            <span className="text-sm text-primary font-medium">
              {result.overallRisk <= 30
                ? "Channel looks safe for monetization"
                : result.overallRisk <= 60
                ? "Some issues need attention"
                : "High demonetization risk detected"}
            </span>
          </div>
          <Button
            variant="neonOutline"
            size="sm"
            className="mt-4 gap-2"
            onClick={() => handleExportPDF(result)}
          >
            <Download className="h-4 w-4" />
            Download Report
          </Button>
        </div>
      </div>

      {/* Check Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {result.checks.map((check) => {
          const config = statusConfig[check.status];
          const StatusIcon = config.icon;
          const CheckIcon = iconMap[check.id] || Shield;

          return (
            <div key={check.id} className={`glass-card p-5 border ${config.bg} space-y-3`}>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <CheckIcon className="h-5 w-5 text-muted-foreground" />
                  <h3 className="font-semibold">{check.label}</h3>
                </div>
                <div className="flex items-center gap-2">
                  <StatusIcon className={`h-5 w-5 ${config.color}`} />
                  <span className={`text-sm font-medium ${config.color}`}>{config.label}</span>
                </div>
              </div>
              <p className="text-sm text-muted-foreground">{check.detail}</p>
              <RiskMeter score={check.score} label="" size="sm" />
            </div>
          );
        })}
      </div>
    </section>
  );
};

export default AuditDashboard;
