import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";

interface PDFReportData {
  title: string;
  url: string;
  thumbnail: string;
  platform: string;
  riskScore: number;
  verdict: string;
  fixRoadmap: string[];
  issues: any[];
  engine: string;
}

/**
 * Professional PDF Report Generator for TubeClear AI
 * Includes Thumbnail, Fix Roadmap, and Bilingual Insights
 */
export const generateAuditPDF = async (data: PDFReportData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // 1. Header Section
  doc.setFillColor(30, 41, 59); // Slate-900
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("TubeClear AI - Audit Report", 15, 25);
  
  doc.setFontSize(10);
  doc.text(`Generated on: ${format(new Date(), "PPP p")}`, pageWidth - 15, 25, { align: "right" });

  // 2. Video Thumbnail & Basic Info
  let currentY = 50;
  
  try {
    // Adding Thumbnail Image
    if (data.thumbnail) {
      // Note: In a real browser env, you might need to proxy the image or use base64
      // to avoid CORS issues with jspdf
      doc.addImage(data.thumbnail, 'JPEG', 15, currentY, 50, 28);
    }
  } catch (e) {
    doc.rect(15, currentY, 50, 28);
    doc.text("No Thumbnail", 25, currentY + 15);
  }

  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(data.title.substring(0, 60) + (data.title.length > 60 ? "..." : ""), 70, currentY + 5);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Platform: ${data.platform.toUpperCase()}`, 70, currentY + 12);
  doc.text(`URL: ${data.url.substring(0, 50)}...`, 70, currentY + 18);
  doc.text(`AI Engine: ${data.engine}`, 70, currentY + 24);

  currentY += 40;

  // 3. Risk & Verdict Section
  doc.setDrawColor(226, 232, 240);
  doc.line(15, currentY, pageWidth - 15, currentY);
  currentY += 10;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Audit Verdict:", 15, currentY);
  
  const verdictColor = data.verdict === "GREEN" ? [34, 197, 94] : data.verdict === "YELLOW" ? [234, 179, 8] : [239, 68, 68];
  doc.setTextColor(verdictColor[0], verdictColor[1], verdictColor[2]);
  doc.text(`${data.verdict} (${data.riskScore}% Risk)`, 50, currentY);

  currentY += 15;

  // 4. Fix Roadmap (Step-by-Step Guide)
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(14);
  doc.text("Fix Roadmap (Actionable Steps)", 15, currentY);
  currentY += 7;
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  
  if (data.fixRoadmap && data.fixRoadmap.length > 0) {
    data.fixRoadmap.forEach((step, index) => {
      const stepText = `${index + 1}. ${step}`;
      const splitStep = doc.splitTextToSize(stepText, pageWidth - 30);
      doc.text(splitStep, 15, currentY);
      currentY += (splitStep.length * 5) + 2;
    });
  } else {
    doc.text("No specific fixes required. Content is safe.", 15, currentY);
    currentY += 10;
  }

  currentY += 5;

  // 5. Detailed Violations Table
  autoTable(doc, {
    startY: currentY,
    head: [['Timestamp', 'Policy Violation', 'Severity', 'Urdu Explanation (Wazahat)']],
    body: data.issues.map(issue => [
      issue.timestamp || "N/A",
      issue.description || "Policy Breach",
      issue.severity?.toUpperCase() || "MEDIUM",
      issue.urduExplanation || "Review karein aur policy ke mutabiq theek karein."
    ]),
    headStyles: { fillColor: [30, 41, 59] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { left: 15, right: 15 }
  });

  // Footer
  const finalY = (doc as any).lastAutoTable.finalY + 20;
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("This report is generated by TubeClear AI. Always review official platform policies.", pageWidth / 2, finalY, { align: "center" });
  doc.text("© 2026 TubeClear AI Compliance Engine", pageWidth / 2, finalY + 5, { align: "center" });

  // Save PDF
  doc.save(`TubeClear_Report_${data.platform}_${Date.now()}.pdf`);
};